#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Sep 22 02:52:14 AST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryShaders_v4.7.2
enableShaders=true
