[lucky]
	#How much MP should this skill cost to acquire/plunder/copy under normal circumstances?
	acquirementCost = 10000.0
	#How much mastery should this skill have by default?
	#Any value above 1 = X Mastery at acquirement
	#0 = Must be learned
	#Any value below 0 = Requires X Learn Points
	acquirementMastery = 0
	luckBonusMastered = 2.0
	luckBonusUnmastered = 1.0
